### ISSUE TITLE
IDMPlusTest.computeAcceleration() does not run

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#125]
`IDMPlusTest` does not run and exits with an exception.

On line 329-341 of `IDMPlusTest` in the method `computeAcceleration()` an exception is thrown at:

```java
  if (timeStep > 120)
  {
      double position = referenceCar40.position(lane, referenceCar40.getFront()).getSI();
```

This method calls:

```java
    public final Length position(final Lane lane, final RelativePosition relativePosition) throws GtuException
    {
        return position(lane, relativePosition, getSimulator().getSimulatorAbsTime());
```

which in turn calls on line 1142 in `LaneBasedGtu`:

```java
    OrientedPoint2d p = plan.getLocation(when, relativePosition);
```

This calls in `OperationalPlan.getLocation()`:

```java
    public final OrientedPoint2d getLocation(final Time time, final RelativePosition pos) throws OperationalPlanException
    {
        double distanceSI = getTraveledDistance(time).si + pos.dx().si;
```

The method `getTraveledDistance` then throws an `OperationalPlanException` at:

```java
        Throw.when(time.si > this.getEndTime().si + 1e-6, OperationalPlanException.class,
                "getTravelDistance exception: requested traveled distance beyond end of plan");
```

**Comment by WJSchakel** [comment]
The issue was that GTUs got deleted upon initialization due to a `NullPointerException` when obtaining objects from `TimeStampedObject`s. Something in the general perception setup has changed to be on-demand, rather than pre-calculated. This involves `DirectDefaultSimplePerception`.

In `LaneBasedGtuFollowingTacticalPlanner` I have added the following lines to update the required perceived information.

```java
        simplePerception.updateForwardHeadwayGtu();
        simplePerception.updateSpeedLimit();
        simplePerception.updateForwardHeadwayObject();
```

Note that this is all old code and will be removed at some point.
