### ISSUE TITLE
LaneChangeModelTest.changeRight() does not run

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#126]
`LaneChangeModelTest.changeRight()` crashes with a `NullPointerException` at line 202:

```java
        LaneMovementStep laneChangeModelResult = laneChangeModel.computeLaneChangeAndAcceleration(
                car, sameLaneGTUs, preferredLaneGTUs, nonPreferredLaneGTUs, new Speed(100, KM_PER_HOUR), 
                new Acceleration(0.3, METER_PER_SECOND_2), new Acceleration(0.1, METER_PER_SECOND_2), 
                new Acceleration(-0.3, METER_PER_SECOND_2));
```

It calls `AbstractLaneChangeModel.computeLaneChangeAndAcceleration(...)` at line 71:

```java
    Lane nonPreferredLane = simplePerception.bestAccessibleAdjacentLane(lane, 
        nonPreferred, longitudinalPosition);
```

which calls `DirectDefaultSimplePerception.bestAccessibleAdjacentLane(...)` at line 553:

```java
        Set<Lane> candidates = getAccessibleAdjacentLanes(lateralDirection).get(currentLane);
```

which calls `DirectDefaultSimplePerception.getAccessibleAdjacentLanes(...)` at line 363:

```java
        return lateralDirection.equals(LateralDirectionality.LEFT) ? this.accessibleAdjacentLanesLeft.object()
                : this.accessibleAdjacentLanesRight.object();
```

resulting in an NPE:

```
java.lang.NullPointerException: Cannot invoke "org.opentrafficsim.base.TimeStampedObject.object()"
because "this.accessibleAdjacentLanesLeft" is null
```

**Comment by WJSchakel** [comment]
The issue was that GTUs got deleted upon initialization due to a `NullPointerException` when obtaining objects from `TimeStampedObject`s. Something in the general perception setup has changed to be on-demand, rather than pre-calculated. This involves `DirectDefaultSimplePerception`.

In `LaneBasedCfLcTacticalPlanner` I have added the following lines to update the required perceived information.

```java
            simplePerception.updateSpeedLimit();
            simplePerception.updateForwardHeadwayGtu();
            simplePerception.updateForwardHeadwayObject();
            simplePerception.updateBackwardHeadway();
            simplePerception.updateNeighboringHeadwaysLeft();
            simplePerception.updateNeighboringHeadwaysRight();
```

In `AbstractLaneChangeModel` I have added the following line to update the required perceived information.

```java
            simplePerception.updateAccessibleAdjacentLanes();
```

Note that this is all old code and will be removed at some point.
