### ISSUE TITLE
Remove `/** {@inheritDoc} */\n`

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#158]

**Comment by WJSchakel** [comment]
The regular expression `^ */\*\* \{@inheritDoc\} \*/\R` being replaced with nothing removes all lines with `/** {@inheritDoc} */`.

But this is sadly not as easy. Methods that are not (effectively) final give the following checkstyle warning if there is no `/** {@inheritDoc} */`:

_"Class 'AnimationBusStopData' looks like designed for extension (can be subclassed), but the method 'toString' does not have javadoc that explains how to do that safely. If class is not designed for extension consider 
making the class 'AnimationBusStopData' final or making the method 'toString' static/final/abstract/empty, or adding allowed annotation for the method."_

Note that `/** {@inheritDoc} */` is essentially pointless if no comments are added to it, because documentation is taken from the super implementation for years already.

An overall replace is thus not possible. But as practice we can leave out `/** {@inheritDoc} */` in any anonymous class or on final methods.

Any better suggestions?

**Comment by averbraeck** [comment]
The rationale for the check in checkstyle is explained here: https://checkstyle.sourceforge.io/checks/design/designforextension.html. In essence, it indicates that any method that can be overridden should have explicit documentation how to do so, or otherwise be declared final or private. Note that `{@inheritDoc}` does not state explicitly how to to replace a method when overriding it, or what the contract of the method is in its particular class. It just copies documentation from the method that it overrides, counting on the fact that the contract of the method is specified there. 

The idea of allowing only final/private/documented methods departs from the standpoint that code should be protected against users who extend the code, overriding a method where it is not clear what the side-effect is when not calling `super.method(...)`. Note that java does not include a mechanism that forces the super method to be called, unless a method is created with an extension hook as explained also in https://checkstyle.sourceforge.io/checks/design/designforextension.html. This is different from constructors where the super constructor is always called, effectively maintaining the contract of the superclass(es) under all circumstances. Overriding some methods, like `toString()` does not have side effects. Overriding `Gtu.move()` without doing a lot of housekeeping breaks the code, and therefore checkstyle indicates that such a method should be properly and explicitly documented to help anyone extending the method (and anyone calling the method in other code) to understand the exact contract of the method.

**Comment by averbraeck** [comment]
In our case, however, the contract is usually explicitly specified in the parent class or parent interface. When implementing an abstract method or interface, the contract stays the same -- it's just implemented. Here, an `{@inheritDoc}` tag does usually not make sense. We implement a well-documented interface or abstract method. In my opinion, we would like checkstyle to **suppress the warming in such a case**.

It is different when overriding an earlier implementation. As an example, a `LanebasedGtu.move()` has a different, and much more extended 'contract' than the `Gtu.move()` method. In a sense, we should be forced to explain what the `LanebasedGtu.move()` 'adds' in addition to or different from the `Gtu.move()` method. In case the `LanebasedGtu.move()` method calls `super.move()` as a statement, the `(@inheritDoc}` can be _included_ in the documentation of the `LanebasedGtu.move()` javadoc, but it should also explain what it does in addition, in case someone wants to override the method and does not understand what needs to be implemented in such a case. In cases like this, checkstyle should **indicate that explicit documentation is needed**. 

So, what do we want checkstyle to do (don't know if we can configure it like this):
- force explicit documentation on interface methods and abstract methods
- force explicit documentation on an override of an already implemented method (which includes overriding a default method in an interface)
- not force documentation on the implementation of an interface method or abstract method, since the contract has already been specified there and can be inherited automatically

**Comment by averbraeck** [comment]
Note that we can change the way checkstyle behaves for our projects by editing the /checks/dsol-checks.xml file in the main pom project. For this particular module it states:

```xml
    <module name="DesignForExtension">
      <property name="severity" value="warning"/>
    </module>
```

In line with the documentation for the DesignForExtension module, we could specify the check to allow methods which have `@Override` annotations to be designed for extension:

```
    <module name="DesignForExtension">
      <property name="ignoredAnnotations" value="Override"/>
    </module>
```

The `DesignForExtension` module also intereferes with the checkstyle module `JavadocMethod`, which ensures that every method and constructor has appropriate Javadoc. It does, however, exclude `@Override` methods by default, as specified in https://checkstyle.sourceforge.io/checks/javadoc/javadocmethod.html. This check is executed for interfaces and classes, and therefore guarantees that the 'root' methods have appropriate javadoc.

**Comment by averbraeck** [comment]
A test shows that the above change indeed results in not necessitating the `{@inheritDoc}` on a non-final method that uses an `@Override`. 

The only downside is that when we extend a method that has already been implemented, we do not force the programmer to state an explicit contract. I consider this to be a minor issue, since we typically include an `{@inheritDoc}` without thinking into the code anyhow... In the documentation about coding style, we could state that in such a case, explicit documentation should be added in case the contract of the method changes.

**Comment by averbraeck** [comment]
@WJSchakel : as far as I am concerned, you can now remove the superfluous `{@inheritDoc}` statements in the entire ots project, and close the issue. I will do the same in our other projects to keep the way we document consistent across our projects.

**Comment by WJSchakel** [comment]
Agreed. They have been removed. In total 2943 instances. Assuming 4 blanks spaces with each, that is 70.362 characters!

The text `/** {@inheritDoc} */` is still in our preferences under Java Code Style > Code Templates > Overriding methods. This shows up when you type `/**` and hit enter above a method that has `@Override`. This behavior is fine, because you very well would want to use that _if_ you are going to write javadoc.
